"""Stage 4 — Assembly. Emits Shotstack JSON + ffmpeg.sh, then renders final.mp4 locally.

Video backgrounds: Pexels video clips (pexels.com/license/ — royalty-free, commercial OK).
Background music:  generated by ffmpeg sine synthesis — zero copyright, YouTube safe.
Closed captions:   burned-in per-shot narration + voiceover.srt for YouTube CC upload.
"""
import shutil
import subprocess
import textwrap

from . import util

# Warm brand gradient palette — one color per shot (cycles if > 8 shots)
_SLIDE_COLORS = [
    (26, 26, 46), (22, 33, 62), (15, 52, 96), (83, 52, 131),
    (45, 106, 79), (27, 67, 50), (64, 145, 108), (82, 183, 136),
]

# System fonts that render Spanish correctly on macOS
_FONT_CANDIDATES = [
    "/System/Library/Fonts/Supplemental/Arial.ttf",
    "/System/Library/Fonts/Helvetica.ttc",
    "/System/Library/Fonts/SFNS.ttf",
    "/System/Library/Fonts/SFNSDisplay.ttf",
]


def _get_font(size):
    try:
        from PIL import ImageFont
        for path in _FONT_CANDIDATES:
            try:
                return ImageFont.truetype(path, size)
            except Exception:
                continue
        return ImageFont.load_default()
    except Exception:
        return None


def _draw_subtitle(draw, width, height, caption, font):
    """Draw Netflix-style subtitle: 2 lines max, bottom-third, semi-transparent bar."""
    from PIL import Image, ImageDraw
    lines = textwrap.wrap(caption, width=42)[:2]
    text = "\n".join(lines)
    if not font:
        return
    bbox = draw.multiline_textbbox((0, 0), text, font=font, spacing=8)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    pad = 20
    bar_y = height - th - pad * 2 - 60
    # Semi-transparent black bar
    bar = Image.new("RGBA", (tw + pad * 2 + 20, th + pad * 2), (0, 0, 0, 160))
    x = (width - bar.width) // 2
    draw._image.paste(bar, (x, bar_y), bar)
    # Text
    tx = (width - tw) // 2
    draw.multiline_text((tx + 2, bar_y + pad + 2), text, font=font,
                        fill=(0, 0, 0, 200), spacing=8, align="center")
    draw.multiline_text((tx, bar_y + pad), text, font=font,
                        fill=(255, 255, 255), spacing=8, align="center")


def _make_slide_photo(width, height, photo_path, caption, out_path):
    """Real photo bg + subtitle-style caption at the bottom."""
    from PIL import Image, ImageDraw, ImageEnhance
    img = Image.open(str(photo_path)).convert("RGBA")
    img = img.resize((width, height), Image.LANCZOS)
    # Slight darken only at the bottom for subtitle legibility
    gradient = Image.new("RGBA", (width, height), (0, 0, 0, 0))
    gd = ImageDraw.Draw(gradient)
    for y in range(height // 2, height):
        alpha = int(140 * (y - height // 2) / (height // 2))
        gd.line([(0, y), (width, y)], fill=(0, 0, 0, alpha))
    img = Image.alpha_composite(img, gradient)
    draw = ImageDraw.Draw(img)
    _draw_subtitle(draw, width, height, caption, _get_font(54))
    img.convert("RGB").save(str(out_path), "PNG")
    return out_path


def _make_slide(width, height, color_rgb, caption, out_path):
    """Color-bg slide + subtitle-style caption (fallback when no Pexels photo)."""
    from PIL import Image, ImageDraw
    img = Image.new("RGBA", (width, height), (*color_rgb, 255))
    draw = ImageDraw.Draw(img)
    _draw_subtitle(draw, width, height, caption, _get_font(54))
    img.convert("RGB").save(str(out_path), "PNG")
    return out_path


def _make_subtitle_overlay(width, height, caption, out_path):
    """Transparent RGBA PNG containing only the subtitle bar — overlaid on video clips."""
    from PIL import Image, ImageDraw
    img = Image.new("RGBA", (width, height), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    _draw_subtitle(draw, width, height, caption, _get_font(54))
    img.save(str(out_path), "PNG")


def _generate_lofi_music(duration_sec, out_path, ffmpeg_bin):
    """Generate royalty-free lofi ambient piano background music using numpy synthesis.

    Style: slow lofi piano pad (72 BPM) — the signature sound of top viral YouTube
    educational/inspirational channels (Lofi Girl, Kurzgesagt, Veritasium style).
    Chord progression: Am7 → Fmaj7 → Cmaj7 → G7 (warm, hopeful, faith-forward).
    Piano envelopes + subtle bass + natural reverb via delay summation.
    Zero copyright — generated entirely from math. YouTube monetization safe.
    """
    try:
        import numpy as np
        import wave as _wave

        sr = 44100
        bpm = 72
        beat_dur = 60.0 / bpm        # 0.833 s per beat
        bar_dur = beat_dur * 4        # 3.333 s per bar

        n = int(sr * (duration_sec + 4))  # extra 4 s for fade-out
        audio = np.zeros(n, dtype=np.float64)

        # 4-voice piano chords: Am7 → Fmaj7 → Cmaj7 → G7
        chords = [
            [220.00, 261.63, 329.63, 392.00],   # Am7:  A3 C4 E4 G4
            [174.61, 220.00, 261.63, 329.63],   # Fmaj7: F3 A3 C4 E4
            [261.63, 329.63, 392.00, 493.88],   # Cmaj7: C4 E4 G4 B4
            [196.00, 246.94, 293.66, 349.23],   # G7:   G3 B3 D4 F4
        ]
        bass_roots = [110.00, 87.31, 130.81, 98.00]   # A2 F2 C3 G2

        bars_total = int(n / sr / bar_dur) + 2

        for bar_i in range(bars_total):
            chord = chords[bar_i % 4]
            start = int(bar_i * bar_dur * sr)
            end = min(int((bar_i + 1) * bar_dur * sr), n)
            if start >= n:
                break
            seg = end - start
            t_seg = np.arange(seg, dtype=np.float64) / sr

            # Piano envelope: 30 ms attack → exponential decay over the bar
            atk = int(0.03 * sr)
            env = np.empty(seg, dtype=np.float64)
            env[:min(atk, seg)] = np.linspace(0.0, 1.0, min(atk, seg))
            if seg > atk:
                env[atk:] = np.exp(-np.arange(seg - atk, dtype=np.float64) / (0.9 * sr))

            for freq in chord:
                # Fundamental + 2nd + 3rd harmonic → piano warmth
                # Slight detune on harmonics for organic "lofi" character
                tone = (
                    np.sin(2 * np.pi * freq * t_seg) * 0.65
                    + np.sin(2 * np.pi * freq * 2.001 * t_seg) * 0.22
                    + np.sin(2 * np.pi * freq * 3.002 * t_seg) * 0.13
                )
                audio[start:end] += tone * env * 0.055

            # Bass note on beat 1 of each bar
            root = bass_roots[bar_i % 4]
            b_len = min(int(beat_dur * sr), n - start)
            t_b = np.arange(b_len, dtype=np.float64) / sr
            b_atk = int(0.015 * sr)
            b_env = np.empty(b_len, dtype=np.float64)
            b_env[:min(b_atk, b_len)] = np.linspace(0.0, 1.0, min(b_atk, b_len))
            if b_len > b_atk:
                b_env[b_atk:] = np.exp(-np.arange(b_len - b_atk, dtype=np.float64) / (0.35 * sr))
            bass_tone = (
                np.sin(2 * np.pi * root * t_b) * 0.65
                + np.sin(2 * np.pi * root * 2 * t_b) * 0.25
            )
            audio[start:start + b_len] += bass_tone * b_env * 0.13

        # Natural reverb: sum 3 delayed copies at decreasing gain
        reverb = audio.copy()
        for delay_ms, gain in [(28, 0.28), (55, 0.16), (110, 0.09)]:
            d = int(delay_ms * sr / 1000)
            reverb[d:] += audio[: n - d] * gain
        audio = reverb

        # Fade in (2 s) and fade out (3 s)
        fi = min(int(2.0 * sr), n)
        fo = min(int(3.0 * sr), n)
        audio[:fi] *= np.linspace(0.0, 1.0, fi)
        audio[-fo:] *= np.linspace(1.0, 0.0, fo)

        # Normalize to −14 dBFS (leaves headroom for mixing under voice)
        peak = np.max(np.abs(audio))
        if peak > 0:
            audio = audio / peak * 0.20

        # Write 16-bit mono WAV, then convert to MP3 with ffmpeg
        tmp_wav = Path(str(out_path)).with_suffix(".wav")
        with _wave.open(str(tmp_wav), "w") as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)
            wf.setframerate(sr)
            wf.writeframes((audio * 32767).astype(np.int16).tobytes())

        r = subprocess.run(
            [ffmpeg_bin, "-y", "-i", str(tmp_wav), "-b:a", "192k", str(out_path)],
            capture_output=True, text=True,
        )
        tmp_wav.unlink(missing_ok=True)
        if r.returncode != 0:
            util.log("assemble", f"music WAV→MP3 failed: {r.stderr[-100:]}")

    except Exception as e:
        util.log("assemble", f"lofi music gen failed ({e}), no background music")


def _shotstack_json(config, storyboard, audio_path):
    w, h = config["assemble"]["resolution"].split("x")
    clips = []
    start = 0.0
    for shot in storyboard:
        dur = shot["duration_hint_sec"]
        clips.append({
            "asset": {"type": "image", "src": f"<<URL for stock: {shot['stock_query']}>>"},
            "start": round(start, 2), "length": dur,
            "effect": "zoomIn",
            "transition": {"in": "fade", "out": "fade"},
        })
        start += dur
    timeline = {
        "soundtrack": {"src": "<<music url>>", "effect": "fadeOut"} if config["assemble"]["background_music"] else None,
        "tracks": [{"clips": clips}],
    }
    return {
        "timeline": timeline,
        "output": {"format": "mp4", "size": {"width": int(w), "height": int(h)}, "fps": config["assemble"]["fps"]},
        "merge": [{"find": "voiceover", "replace": audio_path or "<<voiceover.mp3>>"}],
    }


def _encode_clip_segment(ffmpeg, clip_path, sub_png, w, h, fps, dur, seg_path):
    """Encode a Pexels video clip to a fixed-duration segment with subtitle overlay.

    Scales the clip to fill the frame (Pexels videos are 16:9, same as our target),
    then overlays the transparent subtitle PNG.
    """
    # Scale to fill frame exactly — Pexels clips are 16:9 so no stretch artifacts.
    # setsar=1 corrects Sample Aspect Ratio flags some clips carry.
    cmd = [
        ffmpeg, "-y",
        "-stream_loop", "-1", "-i", str(clip_path),
        "-i", str(sub_png),
        "-filter_complex",
        (
            f"[0:v]scale={w}:{h},setsar=1[bg];"
            f"[1:v]format=rgba[sub];"
            f"[bg][sub]overlay=0:0[v]"
        ),
        "-map", "[v]",
        "-c:v", "libx264", "-pix_fmt", "yuv420p",
        "-t", str(dur), "-r", str(fps),
        seg_path,
    ]
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    return r.returncode == 0, r.stderr


def _encode_photo_segment(ffmpeg, png_path, w, h, fps, dur, seg_path):
    """Encode a static PNG slide (photo or color) to a fixed-duration segment."""
    cmd = [
        ffmpeg, "-y",
        "-loop", "1", "-i", str(png_path),
        "-c:v", "libx264", "-pix_fmt", "yuv420p",
        "-t", str(dur), "-r", str(fps),
        seg_path,
    ]
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    return r.returncode == 0, r.stderr


def _render_local(config, storyboard, audio_path, odir):
    """Render final.mp4 with:
      • Pexels video clips as moving backgrounds (falls back to photo, then color)
      • Burned-in narration subtitles via Pillow overlay
      • Ambient background music mixed at 8% under the voiceover
    """
    res = config["assemble"]["resolution"]
    w, h = res.split("x")
    fps = config["assemble"]["fps"]
    ffmpeg = shutil.which("ffmpeg")
    media_dir = odir / "media"
    media_dir.mkdir(exist_ok=True)

    from core.visuals import _pexels_download, _pexels_video_download
    segment_paths = []
    clip_count = 0

    for i, shot in enumerate(storyboard):
        color_rgb = _SLIDE_COLORS[i % len(_SLIDE_COLORS)]
        dur = shot["duration_hint_sec"]
        caption = shot.get("narration_excerpt", "")
        seg_path = str(media_dir / f"shot_{i:02d}.mp4")
        query = shot.get("stock_query", "")

        # --- Attempt 1: Pexels video clip ---
        clip_path = media_dir / f"clip_{i:02d}.mp4"
        sub_png = media_dir / f"sub_{i:02d}.png"
        _make_subtitle_overlay(int(w), int(h), caption, sub_png)

        have_clip = _pexels_video_download(query, clip_path)
        if have_clip:
            ok, err = _encode_clip_segment(ffmpeg, clip_path, sub_png, w, h, fps, dur, seg_path)
            if ok:
                clip_count += 1
                segment_paths.append(seg_path)
                continue
            util.log("assemble", f"clip encode failed shot {i}, falling back to photo: {err[-120:]}")

        # --- Attempt 2: Pexels photo ---
        png_path = media_dir / f"shot_{i:02d}.png"
        stock_path = media_dir / f"stock_{i:02d}.jpg"
        have_stock = _pexels_download(query, stock_path)
        if have_stock:
            _make_slide_photo(int(w), int(h), stock_path, caption, png_path)
        else:
            _make_slide(int(w), int(h), color_rgb, caption, png_path)

        ok, err = _encode_photo_segment(ffmpeg, png_path, w, h, fps, dur, seg_path)
        if not ok:
            util.log("assemble", f"photo encode failed shot {i}: {err[-120:]}")
            return False
        segment_paths.append(seg_path)

    util.log("assemble", f"shots encoded: {len(segment_paths)} total, {clip_count} video clips")

    # Write concat list
    concat_list = media_dir / "concat.txt"
    concat_list.write_text("\n".join(f"file '{p}'" for p in segment_paths), encoding="utf-8")

    # Generate lofi ambient piano background music (numpy, zero copyright, YouTube safe)
    total_dur = sum(s["duration_hint_sec"] for s in storyboard)
    music_path = media_dir / "background_music.mp3"
    _generate_lofi_music(total_dur, music_path, ffmpeg)
    have_music = music_path.exists() and music_path.stat().st_size > 1000

    out_path = str(odir / "final.mp4")
    if have_music:
        # Mix voice (100%) + lofi music (12%) — clearly audible but never competes with voice
        cmd = [
            ffmpeg, "-y",
            "-f", "concat", "-safe", "0", "-i", str(concat_list),
            "-i", audio_path,
            "-i", str(music_path),
            "-filter_complex",
            "[1:a]volume=1.0[voice];[2:a]volume=0.12[music];"
            "[voice][music]amix=inputs=2:duration=first[audio]",
            "-map", "0:v", "-map", "[audio]",
            "-c:v", "libx264", "-pix_fmt", "yuv420p",
            "-c:a", "aac", "-b:a", "192k",
            "-shortest", out_path,
        ]
    else:
        cmd = [
            ffmpeg, "-y",
            "-f", "concat", "-safe", "0", "-i", str(concat_list),
            "-i", audio_path,
            "-c:v", "libx264", "-pix_fmt", "yuv420p",
            "-c:a", "aac", "-b:a", "192k",
            "-shortest", out_path,
        ]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        util.log("assemble", f"ffmpeg concat error: {r.stderr[-300:]}")
        return False
    util.log("assemble", f"rendered -> {out_path} (music={'yes' if have_music else 'no'})")
    return True


def generate(config, storyboard, audio_path, odir, srt_path=None):
    plan = _shotstack_json(config, storyboard, audio_path)
    util.write_json(odir / "render_shotstack.json", plan)

    res = config["assemble"]["resolution"]
    fps = config["assemble"]["fps"]
    ff = (
        "# After downloading stock per render_shotstack.json into ./media as shot_1.jpg, shot_2.jpg ...\n"
        "# and exporting voiceover to voiceover.mp3, run:\n"
        f"ffmpeg -framerate {fps} -pattern_type glob -i 'media/shot_*.jpg' "
        f"-i voiceover.mp3 -c:v libx264 -pix_fmt yuv420p -s {res} -shortest "
        "-vf \"scale={res}:force_original_aspect_ratio=cover,zoompan=z='min(zoom+0.0005,1.1)'\" "
        "final.mp4\n"
    ).replace("{res}", res)
    util.write_text(odir / "render_ffmpeg.sh", ff)

    have_ffmpeg = bool(shutil.which("ffmpeg"))
    rendered = False
    if have_ffmpeg and audio_path and Path(audio_path).exists():
        rendered = _render_local(config, storyboard, audio_path, odir)

    util.log("assemble", f"render plan written (shotstack json + ffmpeg.sh); ffmpeg installed={have_ffmpeg}; rendered={rendered}")
    return {"shotstack_plan": str(odir / "render_shotstack.json"),
            "ffmpeg_script": str(odir / "render_ffmpeg.sh"),
            "ffmpeg_available": have_ffmpeg,
            "rendered": rendered}


# Allow Path usage in generate()
from pathlib import Path  # noqa: E402
