"""Stage 4 — Assembly. Emits Shotstack JSON + ffmpeg.sh, then renders final.mp4 locally.

Video backgrounds: Pexels video clips (pexels.com/license/ — royalty-free, commercial OK).
Background music:  generated by ffmpeg sine synthesis — zero copyright, YouTube safe.
Closed captions:   burned-in per-shot narration + voiceover.srt for YouTube CC upload.
"""
import shutil
import subprocess
import textwrap

from . import util

# Warm brand gradient palette — one color per shot (cycles if > 8 shots)
_SLIDE_COLORS = [
    (26, 26, 46), (22, 33, 62), (15, 52, 96), (83, 52, 131),
    (45, 106, 79), (27, 67, 50), (64, 145, 108), (82, 183, 136),
]

# System fonts that render Spanish correctly on macOS
_FONT_CANDIDATES = [
    "/System/Library/Fonts/Supplemental/Arial.ttf",
    "/System/Library/Fonts/Helvetica.ttc",
    "/System/Library/Fonts/SFNS.ttf",
    "/System/Library/Fonts/SFNSDisplay.ttf",
]


def _get_font(size):
    try:
        from PIL import ImageFont
        for path in _FONT_CANDIDATES:
            try:
                return ImageFont.truetype(path, size)
            except Exception:
                continue
        return ImageFont.load_default()
    except Exception:
        return None


def _draw_subtitle(draw, width, height, caption, font):
    """Draw Netflix-style subtitle: 2 lines max, bottom-third, semi-transparent bar."""
    from PIL import Image, ImageDraw
    lines = textwrap.wrap(caption, width=42)[:2]
    text = "\n".join(lines)
    if not font:
        return
    bbox = draw.multiline_textbbox((0, 0), text, font=font, spacing=8)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    pad = 20
    bar_y = height - th - pad * 2 - 60
    # Semi-transparent black bar
    bar = Image.new("RGBA", (tw + pad * 2 + 20, th + pad * 2), (0, 0, 0, 160))
    x = (width - bar.width) // 2
    draw._image.paste(bar, (x, bar_y), bar)
    # Text
    tx = (width - tw) // 2
    draw.multiline_text((tx + 2, bar_y + pad + 2), text, font=font,
                        fill=(0, 0, 0, 200), spacing=8, align="center")
    draw.multiline_text((tx, bar_y + pad), text, font=font,
                        fill=(255, 255, 255), spacing=8, align="center")


def _make_slide_photo(width, height, photo_path, caption, out_path):
    """Real photo bg + subtitle-style caption at the bottom."""
    from PIL import Image, ImageDraw, ImageEnhance
    img = Image.open(str(photo_path)).convert("RGBA")
    img = img.resize((width, height), Image.LANCZOS)
    # Slight darken only at the bottom for subtitle legibility
    gradient = Image.new("RGBA", (width, height), (0, 0, 0, 0))
    gd = ImageDraw.Draw(gradient)
    for y in range(height // 2, height):
        alpha = int(140 * (y - height // 2) / (height // 2))
        gd.line([(0, y), (width, y)], fill=(0, 0, 0, alpha))
    img = Image.alpha_composite(img, gradient)
    draw = ImageDraw.Draw(img)
    _draw_subtitle(draw, width, height, caption, _get_font(54))
    img.convert("RGB").save(str(out_path), "PNG")
    return out_path


def _make_slide(width, height, color_rgb, caption, out_path):
    """Color-bg slide + subtitle-style caption (fallback when no Pexels photo)."""
    from PIL import Image, ImageDraw
    img = Image.new("RGBA", (width, height), (*color_rgb, 255))
    draw = ImageDraw.Draw(img)
    _draw_subtitle(draw, width, height, caption, _get_font(54))
    img.convert("RGB").save(str(out_path), "PNG")
    return out_path


def _make_subtitle_overlay(width, height, caption, out_path):
    """Transparent RGBA PNG containing only the subtitle bar — overlaid on video clips."""
    from PIL import Image, ImageDraw
    img = Image.new("RGBA", (width, height), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    _draw_subtitle(draw, width, height, caption, _get_font(54))
    img.save(str(out_path), "PNG")


def _generate_ambient_music(duration_sec, out_path, ffmpeg_bin):
    """Generate royalty-free ambient background music using ffmpeg sine synthesis.

    Produces a soft A-minor pentatonic pad with a pluck envelope that restarts every 3.5 s.
    Uses floor arithmetic for the envelope period since ffmpeg's aevalsrc doesn't have mod().
    Zero copyright — generated programmatically. YouTube monetization safe.
    """
    d = int(duration_sec) + 10
    # Phase within each 3.5-second pluck period using floor: t - 3.5*floor(t/3.5)
    ph = "(t-3.5*floor(t/3.5))"
    expr = (
        f"0.07*sin(2*PI*110*t)*exp(-{ph}*0.5)"
        f"+0.05*sin(2*PI*165*t)*exp(-{ph}*0.5)"
        f"+0.04*sin(2*PI*220*t)*exp(-{ph}*0.5)"
        f"+0.02*sin(2*PI*261*t)*exp(-{ph}*0.5)"
        f"+0.015*sin(2*PI*330*t)*exp(-{ph}*0.5)"
    )
    cmd = [
        ffmpeg_bin, "-y", "-f", "lavfi",
        "-i", f"aevalsrc={expr}:s=44100:d={d}",
        "-af", "lowpass=f=800,highpass=f=55,volume=0.45",
        "-ar", "44100", str(out_path),
    ]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        util.log("assemble", f"music gen failed: {r.stderr[-150:]}")


def _shotstack_json(config, storyboard, audio_path):
    w, h = config["assemble"]["resolution"].split("x")
    clips = []
    start = 0.0
    for shot in storyboard:
        dur = shot["duration_hint_sec"]
        clips.append({
            "asset": {"type": "image", "src": f"<<URL for stock: {shot['stock_query']}>>"},
            "start": round(start, 2), "length": dur,
            "effect": "zoomIn",
            "transition": {"in": "fade", "out": "fade"},
        })
        start += dur
    timeline = {
        "soundtrack": {"src": "<<music url>>", "effect": "fadeOut"} if config["assemble"]["background_music"] else None,
        "tracks": [{"clips": clips}],
    }
    return {
        "timeline": timeline,
        "output": {"format": "mp4", "size": {"width": int(w), "height": int(h)}, "fps": config["assemble"]["fps"]},
        "merge": [{"find": "voiceover", "replace": audio_path or "<<voiceover.mp3>>"}],
    }


def _encode_clip_segment(ffmpeg, clip_path, sub_png, w, h, fps, dur, seg_path):
    """Encode a Pexels video clip to a fixed-duration segment with subtitle overlay.

    Scales the clip to fill the frame (Pexels videos are 16:9, same as our target),
    then overlays the transparent subtitle PNG.
    """
    # Scale to fill frame exactly — Pexels clips are 16:9 so no stretch artifacts.
    # setsar=1 corrects Sample Aspect Ratio flags some clips carry.
    cmd = [
        ffmpeg, "-y",
        "-stream_loop", "-1", "-i", str(clip_path),
        "-i", str(sub_png),
        "-filter_complex",
        (
            f"[0:v]scale={w}:{h},setsar=1[bg];"
            f"[1:v]format=rgba[sub];"
            f"[bg][sub]overlay=0:0[v]"
        ),
        "-map", "[v]",
        "-c:v", "libx264", "-pix_fmt", "yuv420p",
        "-t", str(dur), "-r", str(fps),
        seg_path,
    ]
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    return r.returncode == 0, r.stderr


def _encode_photo_segment(ffmpeg, png_path, w, h, fps, dur, seg_path):
    """Encode a static PNG slide (photo or color) to a fixed-duration segment."""
    cmd = [
        ffmpeg, "-y",
        "-loop", "1", "-i", str(png_path),
        "-c:v", "libx264", "-pix_fmt", "yuv420p",
        "-t", str(dur), "-r", str(fps),
        seg_path,
    ]
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    return r.returncode == 0, r.stderr


def _render_local(config, storyboard, audio_path, odir):
    """Render final.mp4 with:
      • Pexels video clips as moving backgrounds (falls back to photo, then color)
      • Burned-in narration subtitles via Pillow overlay
      • Ambient background music mixed at 8% under the voiceover
    """
    res = config["assemble"]["resolution"]
    w, h = res.split("x")
    fps = config["assemble"]["fps"]
    ffmpeg = shutil.which("ffmpeg")
    media_dir = odir / "media"
    media_dir.mkdir(exist_ok=True)

    from core.visuals import _pexels_download, _pexels_video_download
    segment_paths = []
    clip_count = 0

    for i, shot in enumerate(storyboard):
        color_rgb = _SLIDE_COLORS[i % len(_SLIDE_COLORS)]
        dur = shot["duration_hint_sec"]
        caption = shot.get("narration_excerpt", "")
        seg_path = str(media_dir / f"shot_{i:02d}.mp4")
        query = shot.get("stock_query", "")

        # --- Attempt 1: Pexels video clip ---
        clip_path = media_dir / f"clip_{i:02d}.mp4"
        sub_png = media_dir / f"sub_{i:02d}.png"
        _make_subtitle_overlay(int(w), int(h), caption, sub_png)

        have_clip = _pexels_video_download(query, clip_path)
        if have_clip:
            ok, err = _encode_clip_segment(ffmpeg, clip_path, sub_png, w, h, fps, dur, seg_path)
            if ok:
                clip_count += 1
                segment_paths.append(seg_path)
                continue
            util.log("assemble", f"clip encode failed shot {i}, falling back to photo: {err[-120:]}")

        # --- Attempt 2: Pexels photo ---
        png_path = media_dir / f"shot_{i:02d}.png"
        stock_path = media_dir / f"stock_{i:02d}.jpg"
        have_stock = _pexels_download(query, stock_path)
        if have_stock:
            _make_slide_photo(int(w), int(h), stock_path, caption, png_path)
        else:
            _make_slide(int(w), int(h), color_rgb, caption, png_path)

        ok, err = _encode_photo_segment(ffmpeg, png_path, w, h, fps, dur, seg_path)
        if not ok:
            util.log("assemble", f"photo encode failed shot {i}: {err[-120:]}")
            return False
        segment_paths.append(seg_path)

    util.log("assemble", f"shots encoded: {len(segment_paths)} total, {clip_count} video clips")

    # Write concat list
    concat_list = media_dir / "concat.txt"
    concat_list.write_text("\n".join(f"file '{p}'" for p in segment_paths), encoding="utf-8")

    # Generate ambient background music (royalty-free, ffmpeg sine synthesis)
    total_dur = sum(s["duration_hint_sec"] for s in storyboard)
    music_path = media_dir / "background_music.mp3"
    _generate_ambient_music(total_dur, music_path, ffmpeg)
    have_music = music_path.exists() and music_path.stat().st_size > 1000

    out_path = str(odir / "final.mp4")
    if have_music:
        # Mix voice (100%) + ambient music (8%) — music barely audible, voice always clear
        cmd = [
            ffmpeg, "-y",
            "-f", "concat", "-safe", "0", "-i", str(concat_list),
            "-i", audio_path,
            "-i", str(music_path),
            "-filter_complex",
            "[1:a]volume=1.0[voice];[2:a]volume=0.08[music];"
            "[voice][music]amix=inputs=2:duration=first[audio]",
            "-map", "0:v", "-map", "[audio]",
            "-c:v", "libx264", "-pix_fmt", "yuv420p",
            "-c:a", "aac", "-b:a", "192k",
            "-shortest", out_path,
        ]
    else:
        cmd = [
            ffmpeg, "-y",
            "-f", "concat", "-safe", "0", "-i", str(concat_list),
            "-i", audio_path,
            "-c:v", "libx264", "-pix_fmt", "yuv420p",
            "-c:a", "aac", "-b:a", "192k",
            "-shortest", out_path,
        ]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        util.log("assemble", f"ffmpeg concat error: {r.stderr[-300:]}")
        return False
    util.log("assemble", f"rendered -> {out_path} (music={'yes' if have_music else 'no'})")
    return True


def generate(config, storyboard, audio_path, odir, srt_path=None):
    plan = _shotstack_json(config, storyboard, audio_path)
    util.write_json(odir / "render_shotstack.json", plan)

    res = config["assemble"]["resolution"]
    fps = config["assemble"]["fps"]
    ff = (
        "# After downloading stock per render_shotstack.json into ./media as shot_1.jpg, shot_2.jpg ...\n"
        "# and exporting voiceover to voiceover.mp3, run:\n"
        f"ffmpeg -framerate {fps} -pattern_type glob -i 'media/shot_*.jpg' "
        f"-i voiceover.mp3 -c:v libx264 -pix_fmt yuv420p -s {res} -shortest "
        "-vf \"scale={res}:force_original_aspect_ratio=cover,zoompan=z='min(zoom+0.0005,1.1)'\" "
        "final.mp4\n"
    ).replace("{res}", res)
    util.write_text(odir / "render_ffmpeg.sh", ff)

    have_ffmpeg = bool(shutil.which("ffmpeg"))
    rendered = False
    if have_ffmpeg and audio_path and Path(audio_path).exists():
        rendered = _render_local(config, storyboard, audio_path, odir)

    util.log("assemble", f"render plan written (shotstack json + ffmpeg.sh); ffmpeg installed={have_ffmpeg}; rendered={rendered}")
    return {"shotstack_plan": str(odir / "render_shotstack.json"),
            "ffmpeg_script": str(odir / "render_ffmpeg.sh"),
            "ffmpeg_available": have_ffmpeg,
            "rendered": rendered}


# Allow Path usage in generate()
from pathlib import Path  # noqa: E402
